import React from 'react';
import './Privacy.css';

const Privacy = () => {
  return (
    <div className="privacyWrapper">
      <div className="privacy-text">
        <span className="policy-segment-name">Privacy policy</span>
        <span>This privacy policy (&quot;Policy&quot;) describes how Website Operator (&quot;Website Operator&quot;, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;) collects, protects and uses the personally identifiable information (&quot;Personal Information&quot;) you (&quot;User&quot;, &quot;you&quot; or &quot;your&quot;) may provide on the <a className="privacyLink" target="_blank" rel="nofollow noopener noreferrer" href="https://gamekeeper.ltcodename.com">gamekeeper.ltcodename.com</a> website and any of its products or services (collectively, &quot;Website&quot; or &quot;Services&quot;). It also describes the choices available to you regarding our use of your Personal Information and how you can access and update this information. This Policy does not apply to the practices of companies that we do not own or control, or to individuals that we do not employ or manage.</span>
        <span className="policy-segment-name">Automatic collection of information</span>
        <span>When you visit the Website our servers automatically record information that your browser sends. This data may include information such as your device's IP address, browser type and version, operating system type and version, language preferences or the webpage you were visiting before you came to our Website, pages of our Website that you visit, the time spent on those pages, information you search for on our Website, access times and dates, and other statistics.</span>
        <span className="policy-segment-name">Collection of personal information</span>
        <span>You can visit the Website without telling us who you are or revealing any information by which someone could identify you as a specific, identifiable individual. If, however, you wish to use some of the Website's features, you will be asked to provide certain Personal Information (for example, your name and e-mail address). We receive and store any information you knowingly provide to us when you create an account,  or fill any online forms on the Website.  When required, this information may include your email address, name,  or other Personal Information. You can choose not to provide us with your Personal Information, but then you may not be able to take advantage of some of the Website's features. Users who are uncertain about what information is mandatory are welcome to contact us.</span>
        <span className="policy-segment-name">Use and processing of collected information</span>
        <span>Any of the information we collect from you may be used to personalize your experience; improve our Website; improve customer service and respond to queries and emails of our customers; send notification emails such as password reminders, updates, etc;  run and operate our Website and Services. Information collected automatically is used only to identify potential cases of abuse and establish statistical information regarding Website usage. This statistical information is not otherwise aggregated in such a way that would identify any particular user of the system.</span>
        <span>We may process Personal Information related to you if one of the following applies: &bull; You have given your consent for one or more specific purposes. Note that under some legislations we may be allowed to process information until you object to such processing (by opting out), without having to rely on consent or any other of the following legal bases below. This, however, does not apply, whenever the processing of Personal Information is subject to European data protection law; &bull; Provision of information is necessary for the performance of an agreement with you and/or for any pre-contractual obligations thereof; &bull; Processing is necessary for compliance with a legal obligation to which you are subject; &bull; Processing is related to a task that is carried out in the public interest or in the exercise of official authority vested in us; &bull; Processing is necessary for the purposes of the legitimate interests pursued by us or by a third party. In any case, we will be happy to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Information is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</span>
        <span className="policy-segment-name">Information transfer and storage</span>
        <span>Depending on your location, data transfers may involve transferring and storing your information in a country other than your own. You are entitled to learn about the legal basis of information transfers to a country outside the European Union or to any international organization governed by public international law or set up by two or more countries, such as the UN, and about the security measures taken by us to safeguard your information. If any such transfer takes place, you can find out more by checking the relevant sections of this document or inquire with us using the information provided in the contact section.</span>
        <span className="policy-segment-name">The rights of users</span>
        <span>You may exercise certain rights regarding your information processed by us. In particular, you have the right to do the following: &bull; you have the right to withdraw consent where you have previously given your consent to the processing of your information; &bull; you have the right to object to the processing of your information if the processing is carried out on a legal basis other than consent; &bull; you have the right to learn if information is being processed by us, obtain disclosure regarding certain aspects of the processing and obtain a copy of the information undergoing processing; &bull; you have the right to verify the accuracy of your information and ask for it to be updated or corrected; &bull; you have the right, under certain circumstances, to restrict the processing of your information, in which case, we will not process your information for any purpose other than storing it; &bull; you have the right, under certain circumstances, to obtain the erasure of your Personal Information from us; &bull; you have the right to receive your information in a structured, commonly used and machine readable format and, if technically feasible, to have it transmitted to another controller without any hindrance. This provision is applicable provided that your information is processed by automated means and that the processing is based on your consent, on a contract which you are part of or on pre-contractual obligations thereof.</span>
        <span className="policy-segment-name">The right to object to processing</span>
        <span>Where Personal Information is processed for the public interest, in the exercise of an official authority vested in us or for the purposes of the legitimate interests pursued by us, you may object to such processing by providing a ground related to your particular situation to justify the objection. You must know that, however, should your Personal Information be processed for direct marketing purposes, you can object to that processing at any time without providing any justification. To learn, whether we are processing Personal Information for direct marketing purposes, you may refer to the relevant sections of this document.</span>
        <span className="policy-segment-name">How to exercise these rights</span>
        <span>Any requests to exercise User rights can be directed to the Owner through the contact details provided in this document. These requests can be exercised free of charge and will be addressed by the Owner as early as possible.</span>
        <span className="policy-segment-name">Privacy of children</span>
        <span>We recognize the need to provide further privacy protections with respect to Personal Information we may collect from children and take many special precautions to protect the privacy of children. We do not require a child to disclose more information than is reasonably necessary to use the Website and Services. We encourage children to consult with their parents before submitting any information to any Website, including gamekeeper.ltcodename.com. We believe parents should be involved in the online activities of their children and suggest that parents do their best to provide their children with a safe and friendly online environment.</span>
        <span className="policy-segment-name">Cookies</span>
        <span>The Website uses &quot;cookies&quot; to help personalize your online experience. A cookie is a text file that is placed on your hard disk by a web page server. Cookies cannot be used to run programs or deliver viruses to your computer. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you. We may use cookies to collect, store, and track information for statistical purposes to operate our Website and Services. You have the ability to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. To learn more about cookies and how to manage them, visit <a className="privacyLink" target="_blank" rel="noopener noreferrer" href="https://www.internetcookies.org">internetcookies.org</a></span>
        <span className="policy-segment-name">Do Not Track signals</span>
        <span>Some browsers incorporate a Do Not Track feature that signals to websites you visit that you do not want to have your online activity tracked. Tracking is not the same as using or collecting information in connection with a website. For these purposes, tracking refers to collecting personally identifiable information from consumers who use or visit a website or online service as they move across different websites over time. Our Website does not track its visitors over time and across third party websites. However, some third party sites may keep track of your browsing activities when they serve you content, which enables them to tailor what they present to you.</span>
        <span className="policy-segment-name">Links to other websites</span>
        <span>Our Website contains links to other websites that are not owned or controlled by us. Please be aware that we are not responsible for the privacy practices of such other websites or third-parties. We encourage you to be aware when you leave our Website and to read the privacy statements of each and every website that may collect Personal Information.</span>
        <span className="policy-segment-name">Information security</span>
        <span>We secure information you provide on computer servers in a controlled, secure environment, protected from unauthorized access, use, or disclosure. We maintain reasonable administrative, technical, and physical safeguards in an effort to protect against unauthorized access, use, modification, and disclosure of Personal Information in its control and custody. However, no data transmission over the Internet or wireless network can be guaranteed. Therefore, while we strive to protect your Personal Information, you acknowledge that &bull; there are security and privacy limitations of the Internet which are beyond our control; &bull; the security, integrity, and privacy of any and all information and data exchanged between you and our Website cannot be guaranteed; and &bull; any such information and data may be viewed or tampered with in transit by a third-party, despite best efforts.</span>
        <span className="policy-segment-name">Data breach</span>
        <span>In the event we become aware that the security of the Website has been compromised or users Personal Information has been disclosed to unrelated third parties as a result of external activity, including, but not limited to, security attacks or fraud, we reserve the right to take reasonably appropriate measures, including, but not limited to, investigation and reporting, as well as notification to and cooperation with law enforcement authorities. In the event of a data breach, we will make reasonable efforts to notify affected individuals if we believe that there is a reasonable risk of harm to the user as a result of the breach or if notice is otherwise required by law. When we do, we will post a notice on the Website, send you an email.</span>
        <span className="policy-segment-name">Legal disclosure</span>
        <span>We will disclose any information we collect, use or receive if required or permitted by law, such as to comply with a subpoena, or similar legal process, and when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request.</span>
        <span className="policy-segment-name">Changes and amendments</span>
        <span>We may update this Privacy Policy from time to time in our discretion and will notify you of any material changes to the way in which we treat Personal Information. When changes are made, we will send you an email to notify you. We may also provide notice to you in other ways in our discretion, such as through contact information you have provided. Any updated version of this Privacy Policy will be effective immediately upon the posting of the revised Privacy Policy unless otherwise specified. Your continued use of the Website or Services after the effective date of the revised Privacy Policy (or such other act specified at that time) will constitute your consent to those changes. However, we will not, without your consent, use your Personal Data in a manner materially different than what was stated at the time your Personal Data was collected. Policy was created with <a className="privacyLink" target="_blank" rel="noopener noreferrer" title="Sample privacy policy template" href="https://www.websitepolicies.com/privacy-policy-generator">Website Policies</a>.</span>
        <span className="policy-segment-name">Acceptance of this policy</span>
        <span>You acknowledge that you have read this Policy and agree to all its terms and conditions. By using the Website or its Services you agree to be bound by this Policy. If you do not agree to abide by the terms of this Policy, you are not authorized to use or access the Website and its Services.</span>
        <span className="policy-segment-name">Contacting us</span>
        <span>If you would like to contact us to understand more about this Policy or wish to contact us concerning any matter relating to individual rights and your Personal Information, you may do so via the <a className="privacyLink" target="_blank" rel="nofollow noopener noreferrer" href="https://twitter.com/LtCodename">contact form</a>.</span>
        <span>This document was last updated on September 30, 2019.</span>
      </div>
    </div>
  );
};

export default Privacy;
